version: '2.1'

services:

  zookeeper:
    image: 'wurstmeister/zookeeper'
    hostname: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/signup-service'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

  kafka:
    image: 'wurstmeister/kafka'
    hostname: kafka
    command: [start-kafka.sh]
    ports:
      - '9092:9092'
    links:
      - zookeeper:zk
    volumes:
      - 'kafka_data:/signup-service'
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: >
        validation-email-data:1:1,
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
